
<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <!-- Start Header -->
        <script type="text/javascript">
            //********************** START CONSTANTS
            //********************** END CONSTANTS
            
            //********************** START VARIABLES
//            var urlAboutUs = "<?php // echo $this->url('website', array('action' => 'aboutUs', 'controller' => 'Website')) ?>";
            //********************** END VARIABLES

        </script>
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/theme1.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/themes/ui-lightness/jquery-ui.css')
                ->prependStylesheet($this->basePath() . '/css/themes/ui-lightness/jquery.ui.datepicker.css')
                ->prependStylesheet($this->basePath() . '/css/flexnav.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
//        ->appendStylesheet($this->basePath() . '/css/themes/ui-lightness/jquery-ui.css')
//        ->appendStylesheet($this->basePath() . '/css/themes/ui-lightness/jquery.ui.datepicker.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('/js/all.js'))
                ->prependFile($this->basePath('/js/bootstrap.js'))
                ->prependFile($this->basePath('/js/jquery.flexnav.js'))
                ->prependFile($this->basePath('/js/jquery-ui.js'))
                ->prependFile($this->basePath('/js/jquery.min.js'));
        ?>
        <!-- End Header -->
    </head>
    <body>
        <noscript>
        <div class="noScriptCss"><img src="<?php echo $this->basePath('/img/no_js_en.gif'); ?>" alt="Javascript not enabled" /></div>
        </noscript>
        <div id="loadingImgDiv" class="loadingDivCss"><img src="<?php echo $this->basePath('/img/loading.gif'); ?>" /></div>
        <div id="alertBoxDiv">
            <div id="alertBoxDivSub">
                <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/img/delete.png'); ?>" /></a>
                <h1>Please enter your name.</h1>
            </div>
        </div>
        <!-- ========================================= Start Top-Nav Menu and Top Container ====================================================== -->
        <div id="topBarContainer" class="navbar navbar-default navbar-static-top webTopContainer" role="navigation">
                <div class="container">
                    <div class="webLogoCss mT20" >&nbsp;</div>
                    <div class="webRightVectorBg fR" >&nbsp;</div>
                </div>
                <div id="topNavContainer" class="container bgC-Dm">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <!--<a class="navbar-brand" href="#">Project name</a>-->
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav navAjaxLink">
                            <li class="active"><a href="<?php echo $this->url('website', array('action' => 'index', 'controller' => 'Website')) ?>">HOME</a></li>
                            <li><a href="<?php echo $this->url('website', array('action' => 'aboutUs', 'controller' => 'Website')) ?>">ABOUT US</a></li>
                            <li><a href="<?php echo $this->url('website', array('action' => 'rmsFeature', 'controller' => 'Website')) ?>">RMS FEATURES</a></li>
                            <li>
                                <a href="#contact">CHECK A DEMO</a>
                            </li>
                            <li>
                                <a href="#contact">CREATE NEW ACCOUNT</a>
                            </li>
<!--                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Accounts <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                </ul>
                            </li>-->
<!--                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li class="divider"></li>
                                    <li class="dropdown-header">Nav header</li>
                                    <li><a href="#">Separated link</a></li>
                                    <li><a href="#">One more separated link</a></li>
                                </ul>
                            </li>-->
                        </ul>
                        <ul class="nav navbar-nav navbar-right mR5i">
<!--                            <li><a href="../navbar/">Default</a></li>
                            <li><a href="../navbar-static-top/">Static top</a></li>
                            <li class="active"><a href="./">Fixed top</a></li>-->
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">CONTACT US<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">SIGN IN<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        <!-- ========================================= End Top-Nav Menu and Top Container ====================================================== -->
        
        <!--<div id="containerDiv" class="container">-->
        <div id="containerDiv" class="container-fluid">
            <?php echo $this->content; ?>
        </div> 
        <!-- /container -->
        <!-- Start Footer -->
        <div class="container-fluid bgC-W3 mT15">
            <hr class="b3S-Gr1">
            <footer>
                <div class="bgC-Dm h50">
                    <p class="fL cW5 m5">Copyright &copy; 2005 - <?php echo date('Y') ?>  <?php echo $this->translate('By Resource Management System. All rights reserved.') ?></p>
                    <p class="fR cW5 m5"><?php echo $this->translate('Designed and Developed by Al-Ma\'arijSoft.') ?></p>
                </div>
            </footer>
            <hr class="b3S-Gr1">
        </div>
        <!-- End Footer -->
        <?php echo $this->inlineScript() ?>
    </body>

    <script>
        //****************************Set Ajax On navigation Links
        jQuery('.navAjaxLink a').click(function(event) {
            event.preventDefault();
            var url = jQuery(this).attr('href');
//            alert(url);
            if (url !== '#')
                loadPage(url);
        });
        //****************************Start Scroll Event For MenuBar Effect
        jQuery(window).scroll(function (){
            var topBarContainer = jQuery('#topBarContainer');
            var menuContainer = jQuery('#topNavContainer');
            var top = parseFloat(topBarContainer.height()) - 50;//
           // what the y position of the scroll is
            var y = $(this).scrollTop();
            console.log(y+ '=='+ top);
            
            // whether that's below the form
            if (y >= top) {
              // if so, ad the fixed class
              menuContainer.removeClass('container');
              menuContainer.addClass('container-fluid');
              menuContainer.addClass('navbar-fixed-top');
            } else {
              // otherwise remove it
              menuContainer.addClass('container');
              menuContainer.removeClass('container-fluid');
              menuContainer.removeClass('navbar-fixed-top');
            } 
        });
        //****************************End Scroll Event For MenuBar Effect
    </script>
</html>
