<?php if ($this->pageCount): ?>
    <div class="pagination pagination-centered">
        <ul>
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous; ?>" style="color: #F95507;">
                        ◄
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        ◄
                    </a>
                </li>
            <?php endif; ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route);?>?page=<?php echo $page; ?>" style="color: #F95507;">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->next; ?>" style="color: #F95507;">
                        ►
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        ►
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>