<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <!-- Start Header -->
        <?php echo $this->partial('partial/pdf-style.phtml', 'Application'); ?>
        <!-- End Header -->
<!--    </head>
    <body>
        <div id="loadingImgDiv" class="loadingDivCss"><img src="<?php echo $this->basePath('/img/loading.gif'); ?>" /></div>-->
    </head>
    <body>
        <div id="containerDiv" class="container">


