<div class="topPanelContainer">
    <div class="logoCss"><a href="javascript:loadPage(urlHome);"><img src="<?php echo $this->basePath() ?>/img/logo.png" /></a></div>
    <div class="smallLinksContainer">
        <div class="smallLinksData">Welcome, <?php echo $this->layout()->loginUserName; ?>!&nbsp;&nbsp;&nbsp;</div>
        <div class="smallLinksData"><a href="javascript:logoutUser(urlLogout);">View Profile</a>&nbsp;|</div>
        <div class="smallLinksData"><a href="javascript:logoutUser(urlLogout);">Change Password</a>&nbsp;|</div>
        <div class="smallLinksData"><a href="javascript:logoutUser(urlLogout);">Logout</a>&nbsp;|</div>
        <div class="smallLinksData"><font style="color: #2b073e;">Financial Year: </font><?php echo $this->layout()->currentFinancialYear; ?>&nbsp;</div>
    </div>
    <div class="navContainer"><!--.navContainer -->
        <!--<ul class="nav" id="menu">-->
        <div class="menu-button">Menu</div>
        <?php echo 
        $this->navigation('navigation')
                ->menu()
                ->setUlClass('flexnav')
                ->setMaxDepth(2)
                ->setAcl($this->layout()->ACLObj)
                ->setRole($this->layout()->roleName);
//                ->renderMenu();
        ?>
    </div><!--.navContainer -->
</div>
