<?php //===========================================================================================================   ?>
<?php
echo $this->headScript()->appendFile($this->basePath() . '/js/administration.module.js');
$title = $this->translate('Financial Year');
$this->headTitle($title);
$counter = 0;
?>
<script type="text/javascript">
    var urlAddFinancialYear = "<?php echo $this->url('financial_year', array('action' => 'add', 'controller' => 'FinancialYear')); ?>";
    var urlEditFinancialYear = "<?php echo $this->url('financial_year', array('action' => 'edit', 'controller' => 'FinancialYear')); ?>";
    var urlDeleteFinancialYear = "<?php echo $this->url('financial_year', array('action' => 'delete', 'controller' => 'FinancialYear')); ?>";
</script>
<div id="pageMainDiv">
    <div class="pageHeadingPanel">
        <?php echo $this->headTitle($title); ?>
        <div id="msgTextDiv"></div>
        <!--<div><button id="printprviewbtn" onclick="javascript:loadPage(urlPrintVoucher);" title="Print Report"></button></div>-->
        <div><button id="addbtn" onclick="javascript:loadPage(urlAddFinancialYear);"></button></div>
    </div>
    <div style="clear: both"></div>
    <?php
    $Form = $this->Form;
    $Form->setAttribute('action', $this->url('financial_year', array('action' => 'index', 'controller' => 'FinancialYear')));
    $Form->prepare();
    echo $this->form()->openTag($Form);
    echo $this->formHidden($Form->get('id'));
    ?>
    <div id ="accordion">
        <fieldset>
            <h3>
                <a href="#" class="accordionAnchorHeading">
                    <legend>Search Panel</legend>
                </a>
            </h3>
            <div>
                <div>
                    <?php
                    echo $this->formRow($Form->get('start_date'));
                    echo $this->formRow($Form->get('end_date'));
                    ?>
                </div>
                <div>
                    <?php
                    echo $this->formRow($Form->get('name'));
//                    echo $this->formRow($Form->get('account_code'));
                    ?>
                </div>
                <div>
                    <label class="lblBtnContainer">
                        <input type="button" onclick="refreshPage(urlVoucher);" value="Refresh" />
                        <?php echo $this->formSubmit($Form->get('submit')); ?>
                    </label>
                </div>
            </div>

        </fieldset>

    </div>
    <?php
    echo $this->form()->closeTag();
//                        print_r($Form->getMessages());
    ?>
    <table class="tableCss">
        <thead>
            <tr>
                <th>Sr. No.</th>
                <th>Name</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Actions</th>
            </tr></thead>
        <tbody>
            <?php
            $count = 0;
            foreach ($this->Paginator as $FinancialYear) :
                $counter++;
                $counterSub = 0;
                if ($counter % 2)
                    $rowCss = 'oddRow';
                else
                    $rowCss = 'evenRow';
                ?>
                <tr  class="<?php echo $rowCss; ?>"> 
                    <td><?php echo $counter; ?></td>
                    <td><?php echo $this->escapeHtml($FinancialYear->getName()); ?></td>
                    <td><?php echo $this->escapeHtml($FinancialYear->getStartDate()->format(Application\Library\Application::DATE_FORMAT_FOR_DISPLAY)); ?></td>
                    <td><?php echo $this->escapeHtml($FinancialYear->getEndDate()->format(Application\Library\Application::DATE_FORMAT_FOR_DISPLAY)); ?></td>
                    <td>
                        <a href="javascript:loadPage(urlEditFinancialYear+ '/<?php echo $FinancialYear->getId(); ?>');">Edit</a>
                        <a href="javascript:loadPage(urlDeleteFinancialYear+ '/<?php echo $FinancialYear->getId(); ?>');">Delete</a>
                    </td>

                </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <th colspan="5">&nbsp;</th>
            </tr>    
        </tfoot>
    </table>

    <div class="pagination">
        <?php
        // add at the end of the file after the table
        echo $this->paginationControl(
                // the paginator object
                $this->Paginator,
                // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                'sliding',
                // the partial to use to render the control
                array('partial/paginator.phtml', 'User'),
                // the route to link to when a user clicks a control link
                array(
            'route' => 'user'
                )
        );
        ?>
    </div>
</div>

<script>
    jQuery(document).ready(function() {
        $("#accordion").accordion({
            header: "h3",
            autoheight: false,
            active: 0,
            alwaysOpen: false,
            fillspace: false,
            collapsible: true,
            heightStyle: "content" //heightStyle: content   //auto, fill, content
        });
        //***************************Start Form Submit Event
        jQuery('form').submit(function(event) {
            event.preventDefault();
            postSubmitData(urlVoucher, 'voucherSearch');
        });
        //**********End Form Submit Event
        //Time Interval Functions
        setInterval('hideMsgText()', 20000);
        //===============
        jQuery(function() {
            jQuery('[name="start_date"]').datepicker(dateFormater);
            jQuery('[name="end_date"]').datepicker(dateFormater);
        });
    });
</script>