<div class="container mT20">
    <div class="row">
        <div class="col-md-12">
            <div class="bg-aboutUs">
            </div>
        </div>
    </div>
    <div class="row pT20">
        <div class="col-md-12">
            <div class="w100p bgC-W1 bRd4 p15 b3S-W3 ">
                <h1 class="cP">About Us</h1>
                <p class="pL10 taJ cG1">
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                </p>
            </div>
        </div>
    </div>
</div>