<div class="container-fluid home-bg">
    
</div>
<div class="container mT20">
    <div class="row">
        <div class="col-md-6 bgC-W1 bRd4 p15 ">
            <h1 class="cP">Resource Management System(RMS)</h1>
            <p class="pL10 taJ cG1">
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
            </p>
        </div>
        <div class="col-md-5 communityBox bgC-W1 fR">
            <h1>Available Business Communities</h1>
            <div class="col-md-5 bgC-W0 manufecturalCommunity">
                <div class="w141 h84 mT15 mL7"></div>
                <span>Manufacturing Sector</span>
            </div>
            <div class="col-md-5 bgC-W0 schoolCommunity fR">
                <div class="w141 h84 mT15 mL7"></div>
                <span>Educational Sector</span>
            </div>
        </div>
    </div>
        
</div>