<div class="container-fluid home-bg"></div>
<div class="container mT20">
    <div class="row">
        <div class="col-md-8 ">
            <div class="w100p bgC-W1 bRd4 p15 b3S-W3">
                <h1 class="cP">Resource Management System(RMS)</h1>
                <p class="pL10 taJ cG1">
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                </p>
            </div>
        </div>
        <div class="col-md-4 communityBox bgC-W1 fR b3S-W3">
            <h1>Available Business Communities</h1>
            <div class="col-md-6">
                <div class=" bgC-W0 manufecturalCommunity mL-15 w165 h115">
                    <span class="mT90 dB">Manufacturing Sector</span>
                </div>

            </div>
            <div class="col-md-6">
                <div class=" bgC-W0 schoolCommunity w165 h115">
                    <span class="mT90 dB">Educational Sector</span>
                </div>
            </div>
        </div>
    </div>

    <div class="row mT20">
        <div class="col-md-8">
            <div class="w100p bgC-W1 bRd4 p15 b3S-W3">
                <h1 class="cP">Price and Packages</h1>
                <p class="pL10 taJ cG1">
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                </p>
            </div>
        </div>
        <div class="col-md-4 bgC-W1 communityBox fR b3S-W3">
            <h1>News and Updates</h1>
            <div class="col-md-12">
                <div class="newsContainers bgC-W0 bRd4">
                    <ul class="news m5 taL">
                        <li>
                            <span>July 01, 2014</span>
                            <ul>
                                <li><a>Lorem Ipsum is simply dummy</a></li>
                                <li><a>The printing and typesetting industry</a></li>
                            </ul>
                        </li>
                        <li>
                            <span>July 02, 2014</span>
                            <ul>
                                <li><a>Lorem Ipsum is simply dummy</a></li>
                                <li><a>The printing and typesetting industry</a></li>
                            </ul>
                        </li>
                        <li class="pT10"><a href="#">See More...</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

</div>