<?php //
/*
$this->headScript()->appendFile(
        './fancybox/jquery.fancybox.js?v=2.1.5', 'text/javascript'
);
$this->headScript()->appendFile(
        'http://code.jquery.com/jquery-latest.min.js', 'text/javascript'
);
$this->headLink()->appendStylesheet('/fancybox/jquery.fancybox.css?v=2.1.5');
 */
?>

<!--<script type="text/javascript" src="./fancybox/jquery.fancybox.js?v=2.1.5"></script>-->
<!--<link rel="stylesheet" type="text/css" href="./fancybox/jquery.fancybox.css?v=2.1.5" media="screen" />-->

<a id="various2" class="fancybox" href="
   <?php
   echo $this->url('website', array(
    'action' => 'signup',
));
   ?>
   
   ">Ajax Fancybox</a>
<script type="text/javascript">
    $(document).ready(function() {
        $(".fancybox").fancybox();
    })
</script>