<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('/css/style.css'); ?>">
<?php
echo $this->headScript()->appendFile($this->basePath() . '/js/administration.module.js');
//echo $this->serverUrl("/ERPSystem/css/style.css");
$title = 'Welcome to Login Panel';
$this->headTitle($title);
?>
<html>
    <title>Login Page</title>
    <body margin="0" padding="0" topmargin="0" leftmargin="0" rightmargin="0" bottommargin="0">
        <div class="mainContainerForLoginPage">
            <div class="loginLogoImage">
                <a href="javascript:loadPage(urlHome);"><img src="<?php echo $this->basePath('/img/logo.png') ?>" border="0" /></a>
            </div>
            
            <div class="loginBar"><span><?php echo $this->escapeHtml($title); ?></span></div>
            <div class="loginScreenbg">
                <div class="loginScreen">
                    <?php
                    $Form = $this->Form;
                    $Form->setAttribute('action', $this->url('administration', array('action' => 'login', 'controller' => 'Administration')));
                    $Form->prepare();
                    echo $this->form()->openTag($Form);
                    echo (isset($this->errorMsgs['auth'])) ? '<span class="errorMsgSpan">' . $this->translate($this->errorMsgs['auth']) . '</span>' : '';
                    ?>
                    <div>
                        <?php
                        echo $this->formRow($Form->get('username'));
                        echo $this->formRow($Form->get('password'));
                        ?>
                        <span class="forgotpassword"><a href="#">If you forgot your password?</a></span>
                    </div>
                    <div class="loginbutton">
                        <?php
                        echo $this->formSubmit($Form->get('submit'));
                        ?></div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                </div>
            </div>
            <div class="loginBar" style="font-size: 9px;padding-right: 10px;text-align: right;"><span>Design and Develop By AlmaarijSoft</span></div>
        </div>
    </body>
</html>
