

<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <!-- Start Header -->
        <script type="text/javascript">
            //********************** START CONSTANTS
            //********************** END CONSTANTS

            //********************** START VARIABLES
//            var urlAboutUs = "<?php // echo $this->url('website', array('action' => 'aboutUs', 'controller' => 'Website'))      ?>";
            //********************** END VARIABLES

        </script>
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/theme1.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('/js/all.js'))
                ->prependFile($this->basePath('/js/bootstrap.js'))
                ->prependFile($this->basePath('/js/jquery.min.js'));
        ?>
        <!-- End Header -->
    </head>
    <body>
        <noscript>
        <div class="noScriptCss"><img src="<?php echo $this->basePath('/img/no_js_en.gif'); ?>" alt="Javascript not enabled" /></div>
        </noscript>
        <div id="loadingImgDiv" class="loadingDivCss"><img src="<?php echo $this->basePath('/img/loading.gif'); ?>" /></div>
        <div id="alertBoxDiv">
            <div id="alertBoxDivSub">
                <a href="javascript:void(0);"><img src="<?php echo $this->basePath('/img/delete.png'); ?>" /></a>
                <h1>Please enter your name.</h1>
            </div>
        </div>
        <div id="topBarContainer" class="navbar navbar-default navbar-static-top webTopContainer" role="navigation">
            <div class="container">
                <div class="webLogoCss mT20" >&nbsp;</div>
                <div class="webRightVectorBg fR" >&nbsp;</div>
            </div>
            <div id="topNavContainer" class="container bgC-Dm">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!--<a class="navbar-brand" href="#">Project name</a>-->
                </div>
                <div class="navbar-collapse collapse">
                    
                    
                </div><!--/.nav-collapse -->
            </div>
        </div>
        <!--<div id="containerDiv" class="container">-->
        <div id="containerDiv" class="container-fluid">
            <div class="container mT20">
                <div class="loginScreenbg">
                    <div class="loginScreen">
                        <?php
                        $Form = $this->Form;
                        $Form->setAttribute('action', $this->url('administration', array('action' => 'login', 'controller' => 'Administration')));
                        $Form->prepare();
                        echo $this->form()->openTag($Form);
                        echo (isset($this->errorMsgs['auth'])) ? '<span class="errorMsgSpan">' . $this->translate($this->errorMsgs['auth']) . '</span>' : '';
                        ?>
                        <div>
                            <?php
                            echo $this->formRow($Form->get('username'));
                            echo $this->formRow($Form->get('password'));
                            ?>
                            <span class="forgotpassword"><a href="#">If you forgot your password?</a></span>
                        </div>
                        <div class="loginbutton">
                            <?php
                            echo $this->formSubmit($Form->get('submit'));
                            ?></div>
                        <?php
                        echo $this->form()->closeTag();
                        ?>
                    </div>
                </div>
            </div>

        </div> 
        <!-- /container -->
        <!-- Start Footer -->
        <div class="container-fluid bgC-W3 mT15">
            <hr class="b3S-Gr1">
            <footer>
                <div class="bgC-Dm h50">
                    <p class="fL cW5 m5">Copyright &copy; 2005 - <?php echo date('Y') ?>  <?php echo $this->translate('By Resource Management System. All rights reserved.') ?></p>
                    <p class="fR cW5 m5"><?php echo $this->translate('Designed and Developed by Al-Ma\'arijSoft.') ?></p>
                </div>
            </footer>
            <hr class="b3S-Gr1">
        </div>
        <!-- End Footer -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
