<?php
echo $this->headScript()->appendFile($this->basePath() . '/js/administration.module.js');
$title = $this->translate('Country');
$this->headTitle($title);
$counter = 0;
?>
<script type="text/javascript">
    var urlAddCountry = "<?php echo $this->url('country', array('action' => 'add', 'controller' => 'Country')); ?>";
    var urlEditCountry = "<?php echo $this->url('country', array('action' => 'edit', 'controller' => 'Country')); ?>";
</script>
<div id="pageMainDiv">

    <div class="pageHeadingPanel">
        <?php echo $this->escapeHtml($title); ?>
        <div><button id="printprviewbtn" onclick="javascript:loadPage(urlAddCountry);" title="Print Company"></button></div>
        <div><button id="addbtn" onclick="javascript:loadPage(urlAddCountry);" title="Add Company"></button></div>
    </div>
    <div style="clear: both"></div>
    <table class="tableCss">
        <thead>
            <tr>
                <th>id</th>
                <th>Name</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $count = 0;
            foreach ($this->Paginator as $Country)
            {
                $counter++;
                if ($counter % 2)
                    $rowCss = 'oddRow';
                else
                    $rowCss = 'evenRow';
                ?>
                <tr class="<?php echo $rowCss; ?>">
                    <td><?php echo @$counter; ?></td>
                    <td><?php echo $this->escapeHtml(@$Country->getName()); ?></td>
                    <td>
                        <a href="javascript:loadPage(urlEditVoucher+ '/<?php echo $Country->getId(); ?>');"><img src="<?php echo $this->serverUrl(); ?>/img/btn_view.png" style="border: none;" border="0" title="View Record" /></a>
                        &nbsp;&nbsp;
                        <a href="javascript:loadPage(urlEditVoucher+ '/<?php echo $Country->getId(); ?>');"><img src="<?php echo $this->serverUrl(); ?>/img/btn_edit.png" style="border: none;" border="0" title="Edit Record" /></a>
                        &nbsp;&nbsp;
                        <a href="javascript:loadPage(urlEditVoucher+ '/<?php echo $Country->getId(); ?>');"><img src="<?php echo $this->serverUrl(); ?>/img/delete.png" style="border: none;" border="0" title="Delete Record" /></a>
                    </td>
                </tr>
                <?php
            }
            ?>
        </tbody>
        <tfoot>
            <tr>
                <th colspan="3">&nbsp;</th>
            </tr>    
        </tfoot>
    </table>

    <div class="pagination">
        <?php
        // add at the end of the file after the table
        echo $this->paginationControl(
                // the paginator object
                $this->Paginator,
                // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                'sliding',
                // the partial to use to render the control
                array('partial/paginator.phtml', 'Country'),
                // the route to link to when a user clicks a control link
                array(
            'route' => 'country'
                )
        );
        ?>
    </div>

</div>
