<?php
echo $this->headScript()->appendFile($this->basePath() . '/js/administration.module.js');

$title = 'Add new Group';
$this->headTitle($title);
?>
<div id="pageMainDiv">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <?php
    $Form = $this->Form;
    $Form->setAttribute('action', $this->url('group', array('action' => 'add', 'controller' => 'Group')));
    $Form->prepare();

    echo $this->form()->openTag($Form);
    echo $this->formHidden($Form->get('id'));
    echo $this->formRow($Form->get('name'));
    echo (isset($errorMsgs['name'])) ? '<span class="errorMsgSpan">' . $this->translate($errorMsgs['name']) . '</span>' : '';
    echo $this->formSubmit($Form->get('submit'));
    echo $this->form()->closeTag();
    print_r($Form->getMessages());
    ?>
</div>