<?php
/* <!--========== START FancyBox Popup Style & Script ==========--> */
//echo $this->headLink()->appendStylesheet($this->basePath('assets/plugins/fencybox/jquery.fancybox.css?v=2.1.5'));
//echo $this->headScript()->appendFile($this->basePath('assets/plugins/fencybox/jquery.fancybox.js?v=2.1.5'));
$title = 'FancyBox';
$this->headTitle($title);
?>
<script>
    $(document).ready(function() {
        //*******Start FancyBox
        $(".btn").click(function() {
            $("#myModal").modal('show');
        });
        //*******End FancyBox
    });
</script>
<!--========== End FancyBox Popup Style & Script ==========-->


<!-- ========================================= Start Modal ====================================================== -->
<a href="#myModal" role="button" class="btn btn-large btn-primary" data-toggle="modal">Launch Demo Modal</a>
<div id="myModal" class="modal " tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content loginBox">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h1 class="text-center">Login</h1>
            </div>
            <div class="modal-body">
                <form class="form col-md-12 center-block">
                    <div class="form-group">
                        <input type="text" class="has-error form-control input-lg" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control input-lg" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary btn-lg btn-block">Sign In</button>
                        <span class="pull-right"><a href="#">Register</a></span><span><a href="#">Need help?</a></span>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <div class="col-md-12">
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
                </div>	
            </div>
        </div>
    </div>
</div>
<!-- ========================================= End Modal ====================================================== -->