<?php
echo $this->headScript()->appendFile($this->basePath('/js/account.module.js'));
echo $this->headScript()->appendFile($this->basePath('/js/autocomplete-combo.js'));
$title = $this->translate('Filter Vouchers Report');
$counter = 0;
?>
<script type="text/javascript">
    var urlShowSimpleVoucherReport = "<?php echo $this->url('reporting', array('action' => 'showSimpleVoucherReport', 'controller' => 'Reporting')); ?>";
    var urlShowPdfVoucherReport = "<?php echo $this->url('reporting', array('action' => 'showPdfVoucherReport', 'controller' => 'Reporting')); ?>";
    var urlFilterVoucherReport = "<?php echo $this->url('reporting', array('action' => 'filterVoucherReport', 'controller' => 'Reporting')); ?>";
</script>
<div id="pageMainDiv">
    <div class="pageHeadingPanel">
        <?php echo $this->headTitle($title); ?>
        <div id="msgTextDiv"></div>
        <div><button id="pdfBtn"></button></div>
        <!--<div><button id="excelBtn" onclick="javascript:loadPageInNewWindow(urlVoucherAdd);"></button></div>-->
        <!--<div><button id="printprviewbtn" onclick="javascript:loadPageInNewWindow(urlPrintVoucher);" title="Print Report"></button></div>-->
    </div>
    <div style="clear: both"></div>
    <?php
    $Form = $this->Form;
    $Form->setAttribute('action', $this->url('reporting', array('action' => 'filterVoucherReport', 'controller' => 'reporting')));
    $Form->prepare();
    echo $this->form()->openTag($Form);
    echo $this->formHidden($Form->get('id'));
    ?>
    <div id ="accordion">
        <fieldset>
            <h3>
                <a href="#" class="accordionAnchorHeading">
                    <legend>Search Panel</legend>
                </a>
            </h3>
            <div>
                <div>
                    <?php
                    echo $this->formRow($Form->get('start_date'));
                    echo $this->formRow($Form->get('end_date'));
                    ?>
                </div>
                <div>
                    <?php
                    echo $this->formRow($Form->get('voucher_type'));
                    echo $this->formRow($Form->get('voucher_number'));
                    ?>
                </div>
                <div>
                    <label class="lblBtnContainer">
                        <input type="button" onclick="refreshPage(urlFilterVoucherReport);" value="Refresh" />
                        <?php // echo $this->formSubmit($Form->get('voucherSimpleReport')); ?>
                        <?php echo $this->formSubmit($Form->get('voucherPdfReport')); ?>
                    </label>
                </div>
            </div>

        </fieldset>

    </div>
    <?php
    echo $this->form()->closeTag();
//                        print_r($Form->getMessages());
    ?>
</div>

<script>
    jQuery(document).ready(function() {

        jQuery(function() {
            jQuery('[name="start_date"]').datepicker(dateFormater);
        });
        jQuery(function() {
            jQuery('[name="end_date"]').datepicker(dateFormater);
        });
        $("#accordion").accordion({
            header: "h3",
            autoheight: false,
            active: 0,
            alwaysOpen: false,
            fillspace: false,
            collapsible: true,
            heightStyle: "content" //heightStyle: content   //auto, fill, content
        });
        //****** For account-code Account
        jQuery(function() {
            jQuery("[name='account_code']").combobox();
            jQuery("#toggle").click(function() {
                jQuery("[name='account_code']").toggle();
            });
        });
        //***************************Check which Submit button is clicked
        jQuery('#voucherSimpleReport, #voucherPdfReport').click(function() {
            if (this.id === 'voucherSimpleReport') {
                submitBtnsVals.value = 'Simple Report';
                urlAction = urlShowSimpleVoucherReport;
            }
            else if (this.id === 'voucherPdfReport') {
                submitBtnsVals.value = 'Pdf Report';
                urlAction = urlShowPdfVoucherReport;
            }
        });
        //***************************Start Form Submit Event
        jQuery('form').submit(function(event) {
            event.preventDefault();
//            postSubmitData(urlFilterVoucherReport, 'voucherReporting');
            postSubmitDataAndLoadReportViewer(urlFilterVoucherReport, 'voucherReporting', urlAction);
        });
        //**********End Form Submit Event
        //Time Interval Functions
        setInterval('hideMsgText()', 20000);
        //=======================================================
        jQuery('#pdfBtn').click(function() {
            urlAction = urlShowPdfVoucherReport;
//            event.preventDefault();
            jQuery('form').trigger('submit');
        });
        //========================================================
        jQuery(function() {
            jQuery('[name="voucher_number"]').combobox();
            jQuery("#toggle").click(function() {
                jQuery('[name="voucher_number"]').toggle();
            });
        });
    });
</script>

