<?php
ob_start();

echo $this->doctype();
$title = $this->translate('Reports Viewer');
$counter = 0;
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <!-- Start Header -->
        <title><?php echo $title ?></title>
        <link type="text/css" rel="stylesheet" media="all" href="<?php echo $this->baseUrl . '/css/style.css'; ?>" >
        <!-- End Header -->
    </head>
    <body>
        <div id="loadingImgDiv" class="loadingDivCss"><img src="/RMSForSECHEO/public/img/loading.gif" /></div>
        <div id="containerDiv" class="printViewContainer">
            <div id="printViewPageMainDiv">

                <?php
                $VoucherDetails = $this->VoucherDetails;
                $previousIndexAccountId = 0;
                $nextIndexAccountId = 0;
                $indexPlus = 0;
                $totalDebit = 0;
                $totalCredit = 0;
                $runningBalance = 0;
                $totalRunningBalance = 0;
                $previousDatesBalance = 0;
                $openingBalance = 0;
                $counterSub = 0;
                //===============================================
                $voucherDetailsCount = count($this->VoucherDetails);
                $oBalances = $this->oBalances;
                foreach ($this->VoucherDetails as $index => $VrDetail) :
                    $counter++;
                    $counterSub++;
                    $indexPlus = $index + 1;

                    if ($counterSub % 2)
                        $rowCss = 'oddRow';
                    else
                        $rowCss = 'evenRow';
                    $inverseRowCss = (($rowCss == 'evenRow') ? 'oddRow' : 'evenRow');
                    $Vr = $VrDetail->getVoucher();
                    $accountId = (int) $VrDetail->getAccount()->getId();
                    $accountCode = $VrDetail->getAccount()->getCode();
                    $accountName = $VrDetail->getAccount()->getName();
                    $totalDebit += $VrDetail->getDebit();
                    $totalCredit += $VrDetail->getCredit();
                    $totalRunningBalance = ($totalDebit - $totalCredit);
                    $runningBalance = $runningBalance + (floatval($VrDetail->getDebit()) - floatval($VrDetail->getCredit()));
                    $runningBalanceWithFormat = number_format(abs($runningBalance)) . (($runningBalance > 0) ? ' Dr' : ' Cr');
                    $nextIndexAccountId = (isset($this->VoucherDetails[$indexPlus])) ? $this->VoucherDetails[$indexPlus]->getAccount()->getId() : 0;
                    ?>
                    <?php if ($accountId !== $previousIndexAccountId): ?>
                        <?php
                        $accountOpeningBalance = 0.0;
                        $accountOpeningBalanceWithFormat = '';
                        foreach ($oBalances as $k => $ob):
                            if ($ob['id'] === $accountId):
                                $accountOpeningBalance = $ob['previousDatesOpening'] + $ob['OBalance'];
                                $accountOpeningBalanceWithFormat = Application\Library\Application::showAmountWithDrCr($accountOpeningBalance);
                                unset($oBalances[$k]);
                                break;
                            endif;
                        endforeach;
                        ?>
                        <div style="clear: both;"></div>
                        <div class="reportViewerBody" style="page-break-after: always;">
                            <div class="reportHeadingContainerDiv">
                                <div class="rptLeftSideHeading">
                                    <div class="vrReportRow">
                                        <div class="vrReportHeadColumn vrReportOdd">Financial Year:</div>
                                        <div class="vrReportColumn vrReportOdd"><?php echo $this->layout()->currentFinancialYear; ?></div>
                                    </div> 
                                    <div class="vrReportRow">
                                        <div class="vrReportHeadColumn vrReportEven">From Date:</div>
                                        <div class="vrReportColumn vrReportEven"><?php echo $this->fromDate->format(\Application\Library\Application::DATE_FORMAT_FOR_DISPLAY); ?></div>
                                    </div> 
                                    <div class="vrReportRow">
                                        <div class="vrReportHeadColumn vrReportOdd">To Date:</div>
                                        <div class="vrReportColumn vrReportOdd"><?php echo $this->toDate->format(\Application\Library\Application::DATE_FORMAT_FOR_DISPLAY); ?></div>
                                    </div> 
                                </div>
                                <div class="rptCenterHeading">
                                    <div class="reportLogoInCenter"></div>
                                    <div class="reportHeadingInCenter">General Ledger</div>
                                </div>
                                <div class="rptRightHeading">
                                    <div class="vrReportRow rptRowRight">
                                        <div class="vrReportHeadColumn vrReportOdd">Printed Date:</div>
                                        <div class="vrReportColumn vrReportOdd"><?php echo Application\Library\Application::makeDateTimeObjectForDisplay('now')->format(\Application\Library\Application::DATE_FORMAT_FOR_DISPLAY); ?></div>
                                    </div>
                                    <div class="vrReportRow rptRowRight">
                                        <div class="vrReportHeadColumn vrReportEven">Printed Time:</div>
                                        <div class="vrReportColumn vrReportEven"><?php echo Application\Library\Application::makeDateTimeObjectForDisplay('now')->format(\Application\Library\Application::TIME_FORMAT_FOR_DISPLAY); ?></div>
                                    </div>
                                    <div class="vrReportRow rptRowRight">
                                        <div class="vrReportHeadColumn vrReportOdd"></div>
                                        <div class="vrReportColumn vrReportOdd"></div>
                                    </div>
                                </div>
                            </div>

                            <div class="vrReportParticularsTableDiv">
                                <div id="<?php echo $accountId; ?>" class="accountLedgerInfoBox">
                                    <!--<div class="accountLedgerInfoHeadingDiv"><b>Ledger Account:</b></div>-->
                                    <div class="accountLedgerInfoDetailDiv"><?php echo $accountName . '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(' . $accountCode . ')'; ?></div>
                                </div>
                                <table class="rptTableCss" style="table-layout:fixed; float: left;">
                                    <thead>
                                        <tr>
                                            <th style="width: 8%;">Vr. Date</th>
                                            <th style="width: 8%;">Vr. No</th>
                                            <th style="width: 54%;">Narration</th>
                                            <th style="width: 10%;">Debit</th>
                                            <th style="width: 10%;">Credit</th>
                                            <th style="width: 10%;">Balance</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr class="<?php echo $inverseRowCss; ?>">
                                            <td colspan="6" style="text-align: right;"><?php echo $accountOpeningBalanceWithFormat; ?></td>
                                        </tr>
                                    <?php endif; ?>
                                    <tr class="<?php echo $rowCss; ?>">
                                        <td><?php echo $Vr->getVoucherDate()->format(\Application\Library\Application::DATE_FORMAT); ?></td>
                                        <td><?php echo $Vr->getVoucherNumber(); ?></td>
                                        <td><?php echo $VrDetail->getNarration(); ?></td>
                                        <td style="text-align: right;"><?php echo ($VrDetail->getDebit() ? number_format($VrDetail->getDebit()) : 0); ?></td>
                                        <td style="text-align: right;"><?php echo ($VrDetail->getCredit() ? $VrDetail->getCredit() : 0); ?></td>
                                        <!--<td style="text-align: right;"><?php // echo $runningBalanceWithFormat; ?></td>-->
                                        <td style="text-align: right;"><?php echo Application\Library\Application::showAmountWithDrCr(($runningBalance + $accountOpeningBalance)) ; ?></td>
                                    </tr>
                                    <?php if ($accountId !== $nextIndexAccountId): ?>

                                    </tbody>
                                    <tfoot>
                                        <tr class="<?php echo $inverseRowCss; ?>">
                                            <th colspan="3" style="text-align: right; border-top: 2px #333333 double;">Total Result Of the Account:</th>
                                            <th style="text-align: right; border-top: 2px #333333 double;"><?php echo number_format($totalDebit); ?></th>
                                            <th style="text-align: right; border-top: 2px #333333 double;"><?php echo number_format($totalCredit); ?></th>
                                            <th style="text-align: right; border-top: 2px #333333 double;"><?php echo Application\Library\Application::showAmountWithDrCr(($totalRunningBalance + $accountOpeningBalance)); ?></th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                        <?php
                        $counterSub = 0;
                        $runningBalance = 0;
                        $totalDebit = 0;
                        $totalCredit = 0;
                        $totalRunningBalance = 0;
                        ?>
                    <?php endif; ?>
                    <?php $previousIndexAccountId = $accountId; ?>
                <?php endforeach; ?>
            </div>
        </div> <!-- /container -->
    </body>
</html>
<?php
$html = ob_get_clean();
//================================================
//$exec = \exec('wkhtmltopdf '.$html);
//echo $exec;
//==================================================
//
//echo $html;
$this->Pdf->addPage($html);
$this->Pdf->send();
?>