<?php
echo $this->doctype();
$title = $this->translate('Reports Viewer');
$counter = 0;
//$html = <<<EOD
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <!-- Start Header -->
        <link type="text/css" rel="stylesheet" media="all" href="<?php echo $this->baseUrl.'/css/style.css'; ?>" >
        <!-- End Header -->
    </head>
    <body>
        <div id="loadingImgDiv" class="loadingDivCss"><img src="<?php echo $this->basePath('/img/loading.gif'); ?>" /></div>
        <div id="containerDiv" class="container">
            <div class="printViewPageTopPanelContainer">
                <div class="printViewLogoCss"><img src="<?php echo $this->basePath() ?>/img/logo.png" /></div>
                <div class="printViewTopHeadDataRightSide"><span>Dated:&nbsp;&nbsp;</span><span><?php echo date('d-M-Y'); ?></span></div>
                <div class="printViewHeading"><?php echo $this->headTitle($title); ?></div>
                <div class="printViewTopHeadDataRightSide"><button class="printMe" title="">Print Report</button></div>
            </div>
            <div id="printViewPageMainDiv">
                <?php
                foreach ($this->Vouchers as $Voucher) :
                    $counter++;
                    $counterSub = 0;
                    if ($counter % 2)
                        $rowCss = 'oddRow';
                    else
                        $rowCss = 'evenRow';
                    $VrDetails = $Voucher->getVoucherDetails();
                    ?>
                    <div style="clear: both;"></div>
                    <div class="voucherReportBody" style="page-break-after: always;">
                        <div class="vrReportHeadingContainerDiv">
                            <div class="vrReportLogo"></div>
                            <div class="vrReportHeading"></div>
                        </div>
                        <div class="vrReportBasicInfo">
                            <div class="vrReportRow">
                                <div class="vrReportHeadColumn vrReportOdd">Date:</div>
                                <div class="vrReportColumn vrReportOdd"><?php echo $Voucher->getVoucherDate()->format(\Application\Library\Application::DATE_FORMAT); ?></div>
                            </div>
                            <div class="vrReportRow">
                                <div class="vrReportHeadColumn vrReportEven">Type:</div>
                                <div class="vrReportColumn vrReportEven"><?php echo $Voucher->getVoucherType()->getName(); ?></div>
                            </div>
                            <div class="vrReportRow">
                                <div class="vrReportHeadColumn vrReportOdd">Date:</div>
                                <div class="vrReportColumn vrReportOdd"><?php echo $Voucher->getVoucherNumber(); ?></div>
                            </div>
                        </div>
                        <div class="vrReportParticularsTableDiv">
                            <table class="tableCss" style="float: left;">
                                <thead>
                                    <tr>
                                        <th>Particulars</th>
                                        <th>Debit Amount</th>
                                        <th>Credit Amount</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    $totalDebit = 0;
                                    $totalCredit = 0;
                                    foreach ($VrDetails as $key => $VrDetail):
                                        $counterSub++;
                                        if ($counterSub % 2)
                                            $rowCss = 'oddRow';
                                        else
                                            $rowCss = 'evenRow';
                                        $totalDebit += $VrDetail->getDebit();
                                        $totalCredit += $VrDetail->getCredit();
                                        ?>
                                        <tr class="<?php echo $rowCss; ?>">
                                            <td><?php echo $VrDetail->getAccount()->getName() . ' [' . $VrDetail->getAccount()->getCode() . ']'; ?></td>
                                            <td><?php echo ($VrDetail->getDebit() ? $VrDetail->getDebit() : 0); ?></td>
                                            <td><?php echo ($VrDetail->getCredit() ? $VrDetail->getCredit() : 0); ?></td>
                                        </tr>
                                        <?php
                                    endforeach;
                                    ?>
                                    <tr class="<?php echo $rowCss == 'evenRow' ? 'oddRow' : 'evenRow'; ?>" style="border-top: 2px #B178CF dotted;">
                                        <td>Total Amount:</td>
                                        <td><?php echo $totalDebit; ?></td>
                                        <td><?php echo $totalCredit; ?></td>
                                    </tr>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th colspan="3"></th>
                                    </tr>    
                                </tfoot>
                            </table>
                        </div>
                    </div>
                    <?php
                endforeach;
                ?>
            </div>
        </div> <!-- /container -->
    </body>
</html>
<script>
    jQuery(document).ready(function() {
        jQuery('.printMe').click(function() {
            window.print();
            return false;
        });
    });
    //    //finish loading Img for Reporting Viewer
    //    $(window).preLoad(function() {
    //        jQuery('#loadingImgDiv').show();
    //    });
    //    $(window).load(function() {
    //        jQuery('#loadingImgDiv').hide();
    //    });
</script>