<?php
echo $this->headScript()->appendFile($this->basePath() . '/js/administration.module.js');

$title = 'Add new Branch';
$this->headTitle($title);
?>
<div  id="pageMainDiv">
    <fieldset>
        <h3>
            <a href="#" class="accordionAnchorHeading"><legend><?php echo $this->escapeHtml($title); ?></legend></a></h3>
        <div>
            <?php
            $Form = $this->Form;
            $Form->setAttribute('action', $this->url('branch', array('action' => 'edit', 'controller' => 'Branch', 'id' => $this->id)));
            $Form->prepare();

            echo $this->form()->openTag($Form);
            echo $this->formHidden($Form->get('id'));
            echo $this->formRow($Form->get('company'));
            echo $this->formRow($Form->get('name'));
            echo $this->formRow($Form->get('branch_type'));
            echo $this->formRow($Form->get('country'));
            echo $this->formRow($Form->get('state'));
            echo $this->formRow($Form->get('city'));
            echo $this->formRow($Form->get('zip_code'));
            echo $this->formRow($Form->get('address'));
            echo $this->formRow($Form->get('email'));
            echo $this->formRow($Form->get('cell'));
            echo $this->formRow($Form->get('phone1'));
            echo $this->formRow($Form->get('phone2'));
            echo $this->formRow($Form->get('fax'));
            echo $this->formRow($Form->get('status'));
            echo $this->formRow($Form->get('description'));
            echo $this->formSubmit($Form->get('submit'));
            echo $this->form()->closeTag();
            print_r($Form->getMessages());
            ?>
        </div>
    </fieldset>
</div>
<script type="text/javascript">
    jQuery('select[name="country"]').change(function() {
        SelectBoxNullValue = "Select State";
        errorMsg = "Please select State";
        var url = "<?php echo $this->url('branch', array('action' => 'populateState', 'controller' => 'Branch')) ?>";
        url = url + '/' + jQuery('select[name="country"]').val();
        populateSelectBox(url, 'country', 'state');

    });
    jQuery('select[name="state"]').change(function() {
        SelectBoxNullValue = "Select City";
        errorMsg = "Please select City";
        var url = "<?php echo $this->url('branch', array('action' => 'populateCity', 'controller' => 'Branch')) ?>";
        url = url + '/' + jQuery('select[name="state"]').val();
        populateSelectBox(url, 'state', 'city');

    });

</script>