<?php
echo $this->headScript()->appendFile($this->basePath() . '/js/administration.module.js');
$title = $this->translate('My Company');
$this->headTitle($title);
$counter = 0;
?>
<script type="text/javascript">
    var urlAddCompany = "<?php echo $this->url('company', array('action' => 'add', 'controller' => 'Company')); ?>";
    var urlEditCompany = "<?php echo $this->url('company', array('action' => 'edit', 'controller' => 'Company')); ?>";
</script>
<div id="pageMainDiv">

    <div class="pageHeadingPanel">
        <?php echo $this->escapeHtml($title); ?>
        <div><button id="printprviewbtn" onclick="javascript:loadPage(urlAddCompany);" title="Print Company"></button></div>
        <div><button id="addbtn" onclick="javascript:loadPage(urlAddCompany);" title="Add Company"></button></div>
    </div>
    <div style="clear: both"></div>
    <table class="tableCss">
        <thead>
            <tr>
                <th>Sr. No.</th>
                <th>Name</th>
                <th>Status</th>
                <th>Actions</th>
            </tr></thead>
        <tbody> 
            <?php
            $count = 0;
            foreach ($this->Paginator as $Company) :
                $counter++;
                if ($counter % 2)
                    $rowCss = 'oddRow';
                else
                    $rowCss = 'evenRow';
                ?>
                <tr class="<?php echo $rowCss; ?>">
                    <td><?php echo $counter; ?></td>
                    <td><?php echo $this->escapeHtml($Company->getName()); ?></td>
                    <td><?php echo ($Company->getStatus() ? 'Active' : 'Inactive'); ?></td>
                    <td>
                        <a href="javascript:loadPage(urlEditVoucher+ '/<?php echo $Company->getId(); ?>');"><img src="<?php echo $this->serverUrl(); ?>/img/btn_view.png" style="border: none;" border="0" title="View Record" /></a>
                        &nbsp;&nbsp;
                        <a href="javascript:loadPage(urlEditVoucher+ '/<?php echo $Company->getId(); ?>');"><img src="<?php echo $this->serverUrl(); ?>/img/btn_edit.png" style="border: none;" border="0" title="Edit Record" /></a>
                        &nbsp;&nbsp;
                        <a href="javascript:loadPage(urlEditVoucher+ '/<?php echo $Company->getId(); ?>');"><img src="<?php echo $this->serverUrl(); ?>/img/delete.png" style="border: none;" border="0" title="Delete Record" /></a>
                    </td>
                </tr>
            <?php endforeach; ?></tbody>
        <tfoot>
            <tr>
                <th colspan="4">&nbsp;</th>
            </tr>    
        </tfoot>
    </table>

    <div class="pagination">
        <?php
        echo $this->paginationControl(
                $this->Paginator, 'sliding', array('partial/paginator.phtml', 'Company'), array(
            'route' => 'company'
                )
        );
        ?>
    </div>
</div>
