<?php
echo $this->headScript()->appendFile($this->basePath('/js/account.module.js'));
echo $this->headScript()->appendFile($this->basePath('/js/autocomplete-combo.js'));
$title = $this->translate('List Of Vouchers');
$counter = 0;
?>
<script type="text/javascript">
    var urlPrintVoucher = "<?php echo $this->url('voucher', array('action' => 'printPreview', 'controller' => 'Voucher')); ?>";
    var urlPdfVoucher = "<?php echo $this->url('voucher', array('action' => 'pdfReport', 'controller' => 'Voucher')); ?>";
    var urlEditVoucher = "<?php echo $this->url('voucher', array('action' => 'edit', 'controller' => 'Voucher')); ?>";
    var urlDeleteVoucher = "<?php echo $this->url('voucher', array('action' => 'delete', 'controller' => 'Voucher')); ?>";
</script>
<div id="pageMainDiv">
    <div class="pageHeadingPanel">
        <?php echo $this->headTitle($title); ?>
        <div id="msgTextDiv"></div>
        <div><button id="pdfBtn" onclick="javascript:loadPageInNewWindow(urlPdfVoucher);"></button></div>
        <div><button id="excelBtn" onclick="javascript:loadPageInNewWindow(urlVoucherAdd);"></button></div>
        <div><button id="printprviewbtn" onclick="javascript:loadPageInNewWindow(urlPrintVoucher);" title="Print Report"></button></div>
        <div><button id="addbtn" onclick="javascript:loadPage(urlVoucherAdd);"></button></div>
    </div>
    <div style="clear: both"></div>
    <?php
    $Form = $this->Form;
    $Form->setAttribute('action', $this->url('voucher', array('action' => 'index', 'controller' => 'Voucher')));
    $Form->prepare();
    echo $this->form()->openTag($Form);
    echo $this->formHidden($Form->get('id'));
    ?>
    <div id ="accordion">
        <fieldset>
            <h3>
                <a href="#" class="accordionAnchorHeading">
                    <legend>Search Panel</legend>
                </a>
            </h3>
            <div>
                <div>
                    <?php
                    echo $this->formRow($Form->get('voucher_date'));
                    echo $this->formRow($Form->get('voucher_type'));
                    ?>
                </div>
                <div>
                    <?php
                    echo $this->formRow($Form->get('voucher_number'));
                    echo $this->formRow($Form->get('account_code'));
                    ?>
                </div>
                <div>
                    <label class="lblBtnContainer">
                        <input type="button" onclick="refreshPage(urlVoucher);" value="Refresh" />
                        <?php echo $this->formSubmit($Form->get('submit')); ?>
                    </label>
                </div>
            </div>

        </fieldset>

    </div>
    <?php
    echo $this->form()->closeTag();
//                        print_r($Form->getMessages());
    ?>
    <table class="tableCss">
        <thead>
            <tr>
                <th>Date</th>
                <th>Vr. Type</th>
                <th>Vr. No.</th>
                <th>Actions</th>
            </tr>
        </thead>
        <?php
        $Vouchers = $this->Paginator;
//        if (count($SearchResults) > 0)
//        {
//            $Vouchers = $SearchResults;
//        }
        $counter = 0;
        foreach ($Vouchers as $Voucher) :
            $counter++;
            $counterSub = 0;
            if ($counter % 2)
                $rowCss = 'oddRow';
            else
                $rowCss = 'evenRow';
            ?>
            <tr class="header <?php echo $rowCss; ?>">
                <td><span>▼</span> <?php echo $Voucher->getVoucherDate()->format(\Application\Library\Application::DATE_FORMAT); ?></td>
                <td><?php echo $Voucher->getVoucherType()->getName(); ?></td>
                <td><?php echo $Voucher->getVoucherNumber(); ?></td>
                <td>
                    <a href="javascript:loadPage(urlEditVoucher+ '/<?php echo $Voucher->getId(); ?>');"><img src="<?php echo $this->basePath(); ?>/img/btn_view.png" style="border: none;" border="0" title="View Record" /></a>
                    &nbsp;&nbsp;
                    <a href="javascript:loadPage(urlEditVoucher+ '/<?php echo $Voucher->getId(); ?>');"><img src="<?php echo $this->basePath(); ?>/img/btn_edit.png" style="border: none;" border="0" title="Edit Record" /></a>
                    &nbsp;&nbsp;
                    <a href="javascript:deleteRecord(urlDeleteVoucher+ '/<?php echo $Voucher->getId(); ?>');"><img src="<?php echo $this->basePath(); ?>/img/delete.png" style="border: none;" border="0" title="Delete Record" /></a>
                </td>
            </tr>
            <tr>
                <td colspan="4">
                    <?php $VrDetails = $Voucher->getVoucherDetails(); ?>
                    <table>
                        <thead>
                            <tr>
                                <th>Account Code</th>
                                <th>Account Name</th>
                                <th>Debit</th>
                                <th>Credit</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($VrDetails as $key => $VrDetail):
                                $counterSub++;
                                if ($counterSub % 2)
                                    $rowCss = 'oddRow';
                                else
                                    $rowCss = 'evenRow';
                                ?>
                                <tr class="<?php echo $rowCss; ?>">
                                    <td><?php echo $VrDetail->getAccount()->getCode(); ?></td>
                                    <td><?php echo $VrDetail->getAccount()->getName(); ?></td>
                                    <td><?php echo $VrDetail->getDebit(); ?></td>
                                    <td><?php echo $VrDetail->getCredit(); ?></td>
                                </tr>
                                <?php
                            endforeach;
                            ?>
                        </tbody>
                    </table>
                </td>
            </tr>
        <?php endforeach; ?>
        <tfoot>
            <tr>
                <th colspan="4">&nbsp;</th>
            </tr>    
        </tfoot>

    </table>

    <div class="pagination">
        <?php
        // add at the end of the file after the table
        echo $this->paginationControl(
                // the paginator object
                $this->Paginator,
                // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                'sliding',
                // the partial to use to render the control
                array('partial/paginator.phtml', 'Voucher'),
                // the route to link to when a user clicks a control link
                array(
            'route' => 'voucher'
                )
        );
        ?>
    </div>
</div>

<script>
    jQuery('.header').click(function() {
        jQuery(this).find('span').text(function(_, value) {
            return value == '▼' ? '►' : '▼'
        });
        jQuery(this).nextUntil('tr.header').slideToggle('slow', function() {
        });
        //        jQuery(this).wrapAll('<div />').nextUntil('tr.header').slideToggle('slow', function() {
//            $('.header').closest('div').remove();
//        });
    });
    jQuery(document).ready(function() {
        jQuery(function() {
            jQuery('[name="voucher_date"]').datepicker(dateFormater);
        });
        $("#accordion").accordion({
            header: "h3",
            autoheight: false,
            active: 0,
            alwaysOpen: false,
            fillspace: false,
            collapsible: true,
            heightStyle: "content" //heightStyle: content   //auto, fill, content
        });
        //****** For account-code Account
        jQuery(function() {
            jQuery("[name='account_code']").combobox();
            jQuery("#toggle").click(function() {
                jQuery("[name='account_code']").toggle();
            });
        });
        //***************************Start Form Submit Event
        jQuery('form').submit(function(event) {
            event.preventDefault();
            postSubmitData(urlVoucher, 'voucherSearch');
        });
        //**********End Form Submit Event
        //Time Interval Functions
        setInterval('hideMsgText()', 20000);
    });
</script>

