<?php echo $this->partial('partial/pdf-header', 'Application'); ?>
<?php
//echo $this->headScript()->appendFile($this->basePath() . '/js/account.module.js');
$title = $this->translate('List Of Vouchers');
$counter = 0;
?>
<div class="printViewPageTopPanelContainer">
    <div class="printViewLogoCss"><img src="<?php echo $this->basePath('/img/logo.png') ?>" /></div>
    <div class="printViewTopHeadDataRightSide"><span>Dated:&nbsp;&nbsp;</span><span><?php echo date('d-M-Y'); ?></span></div>
    <div class="printViewHeading"><?php echo $this->headTitle($title); ?></div>
</div>
<div id="printViewPageMainDiv">

    <table class="tableCss">
        <thead>
            <tr>
                <th>Date</th>
                <th>Vr. Type</th>
                <th>Vr. No.</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->Paginator as $Voucher) :
                $counter++;
                $counterSub = 0;
                if ($counter % 2)
                    $rowCss = 'oddRow';
                else
                    $rowCss = 'evenRow';
                ?>
                <tr class="header <?php echo $rowCss; ?>">
                    <td><span><img src="<?php echo $this->serverUrl('/RMSForSECHEO/img/arrowDown.png'); ?>" style="border: none;" border="0" /></span> <?php echo $Voucher->getVoucherDate()->format('d-m-Y'); ?></td>
                    <td><?php echo $Voucher->getVoucherNumber(); ?></td>
                    <td><?php echo $Voucher->getVoucherType()->getName(); ?></td>
                </tr>
                <tr>
                    <td colspan="3">
                        <?php $VrDetails = $Voucher->getVoucherDetails(); ?>
                        <table>
                            <thead>
                                <tr>
                                    <th>Account Code</th>
                                    <th>Account Name</th>
                                    <th>Debit</th>
                                    <th>Credit</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                foreach ($VrDetails as $key => $VrDetail):
                                    $counterSub++;
                                    if ($counterSub % 2)
                                        $rowCss = 'oddRow';
                                    else
                                        $rowCss = 'evenRow';
                                    ?>
                                    <tr class="<?php echo $rowCss; ?>">
                                        <td><?php echo $VrDetail->getAccount()->getCode(); ?></td>
                                        <td><?php echo $VrDetail->getAccount()->getName(); ?></td>
                                        <td><?php echo $VrDetail->getDebit(); ?></td>
                                        <td><?php echo $VrDetail->getCredit(); ?></td>
                                    </tr>
                                    <?php
                                endforeach;
                                ?>
                            </tbody>
                        </table>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <th colspan="3">&nbsp;</th>
            </tr>    
        </tfoot>

    </table>
</div>
<?php echo $this->partial('partial/pdf-footer', 'Application'); ?>
