<?php
echo $this->headScript()->appendFile($this->basePath() . '/js/administration.module.js');
echo $this->headScript()->appendFile($this->basePath('/js/autocomplete-combo.js'));
$title = $this->translate('Opening Balances');
//$this->headTitle($title);
$counter = 0;
?>
<script type="text/javascript">
    var urlAddOpeningBalance = "<?php echo $this->url('opening_balance', array('action' => 'add', 'controller' => 'OpeningBalance')); ?>";
    var urlEditOpeningBalance = "<?php echo $this->url('opening_balance', array('action' => 'edit', 'controller' => 'OpeningBalance')); ?>";
    var urlDeleteOpeningBalance = "<?php echo $this->url('opening_balance', array('action' => 'delete', 'controller' => 'OpeningBalance')); ?>";
</script>
<div id="pageMainDiv">
    <div class="pageHeadingPanel">
        <?php echo $this->headTitle($title); ?>
        <div id="msgTextDiv"></div>
        <!--<div><button id="printprviewbtn" onclick="javascript:loadPage(urlPrintVoucher);" title="Print Report"></button></div>-->
        <div><button id="addbtn" onclick="javascript:loadPage(urlAddOpeningBalance);"></button></div>
    </div>
    <div style="clear: both"></div>
    <?php
    $Form = $this->Form;
    $Form->setAttribute('action', $this->url('opening_balance', array('action' => 'index', 'controller' => 'OpeningBalance')));
    $Form->prepare();
    echo $this->form()->openTag($Form);
    ?>
    <div id ="accordion">
        <fieldset>
            <h3>
                <a href="#" class="accordionAnchorHeading">
                    <legend>Search Panel</legend>
                </a>
            </h3>
            <div>
                <div>
                    <?php
                    echo $this->formRow($Form->get('financial_year'));
                    echo $this->formRow($Form->get('account'));
                    ?>
                </div>
                <div>
                    <label class="lblBtnContainer">
                        <input type="button" onclick="refreshPage(urlOpeningBalance);" value="Refresh" />
                        <?php echo $this->formSubmit($Form->get('submit')); ?>
                    </label>
                </div>
            </div>

        </fieldset>

    </div>
    <?php
    echo $this->form()->closeTag();
//                        print_r($Form->getMessages());
    ?>
    <table class="tableCss">
        <thead>
            <tr>
                <th>Sr. No.</th>
                <th>Financial Year</th>
                <th>Account Name</th>
                <th>Account Code</th>
                <th>Debit</th>
                <th>Credit</th>
                <th>Actions</th>
            </tr></thead>
        <tbody>
            <?php
            foreach ($this->Paginator as $OpeningBalance) :
                $counter++;
                if ($counter % 2)
                    $rowCss = 'oddRow';
                else
                    $rowCss = 'evenRow';
                ?>
                <tr  class="<?php echo $rowCss; ?>"> 
                    <td><?php echo @$counter; ?></td>
                    <td><?php echo $this->translate(@$OpeningBalance->getFinancialYear()->getName()); ?></td>
                    <td><?php echo $this->translate(@$OpeningBalance->getAccount()->getName()); ?></td>
                    <td><?php echo $this->translate(@$OpeningBalance->getAccount()->getCode()); ?></td>
                    <td><?php echo number_format($OpeningBalance->getDebit()); ?></td>
                    <td><?php echo number_format(@$OpeningBalance->getCredit()); ?></td>
                    <td>
                        <a href="javascript:loadPage(urlEditOpeningBalance+ '/<?php echo $OpeningBalance->getId(); ?>');"><img src="<?php echo $this->basePath('/img/btn_edit.png'); ?>" style="border: none;" border="0" title="Edit Record" /></a>
                        <a href="javascript:loadPage(urlDeleteOpeningBalance+ '/<?php echo $OpeningBalance->getId(); ?>');"><img src="<?php echo $this->basePath('/img/delete.png'); ?>" style="border: none;" border="0" title="Delete Record" /></a>
                    </td>

                </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <th colspan="7">&nbsp;</th>
            </tr>    
        </tfoot>
    </table>

    <div class="pagination">
        <?php
        // add at the end of the file after the table
        echo $this->paginationControl(
                // the paginator object
                $this->Paginator,
                // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                'sliding',
                // the partial to use to render the control
                array('partial/paginator.phtml', 'OpeningBalance'),
                // the route to link to when a user clicks a control link
                array(
            'route' => 'opening_balance'
                )
        );
        ?>
    </div>
</div>

<script>
    jQuery(document).ready(function() {
        $("#accordion").accordion({
            header: "h3",
            autoheight: false,
            active: 0,
            alwaysOpen: false,
            fillspace: false,
            collapsible: true,
            heightStyle: "content" //heightStyle: content   //auto, fill, content
        });
        //***************************Start Form Submit Event
        jQuery('form').submit(function(event) {
            event.preventDefault();
            postSubmitData(urlOpeningBalance, 'frmOpeningBalanceSearch');
        });
        //**********End Form Submit Event
        //Time Interval Functions
        setInterval('hideMsgText()', 20000);
        //===============
        jQuery(function() {
            jQuery('[name="start_date"]').datepicker(dateFormater);
            jQuery('[name="end_date"]').datepicker(dateFormater);
        });
        //========================================================
        jQuery(function() {
            jQuery('[name="financial_year"]').combobox();
            jQuery("#toggle").click(function() {
                jQuery('[name="financial_year"]').toggle();
            });
        });
        //========================================================
        jQuery(function() {
            jQuery('[name="account"]').combobox();
            jQuery("#toggle").click(function() {
                jQuery('[name="account"]').toggle();
            });
        });
        //==================================================
    });
</script>